
version: '3.9'

services:
  app:
    container_name: logs-app
    build: ./app
    ports:
      - '8080:8080'

  client:
    container_name: logs-client
    build: ./client
    environment:
      BASE_URL: 'http://logs-app:8080'

