version: '3.9'

services:

  app:
    container_name: logs-app-01
    build: ./app
    ports:
      - '8080:8080'
    volumes:
      - shared-volume:/var/log/app/
      - ./01-app-logging.xml:/app-logging.xml
    environment:
      # Application: use custom log config + log to file
      LOGGING_CONFIG: /app-logging.xml
      LOGGING_FILE_NAME: /var/log/app/app.log
      # APM agent configuration & credentials provided from .env file
      ELASTIC_APM_SERVER_URL: "${apm_server_url}"
      ELASTIC_APM_SECRET_TOKEN: "${apm_secret_token}"
      # APM agent static configuration
      ELASTIC_APM_SERVICE_NAME: app-01
      ELASTIC_APM_CLOUD_PROVIDER: none

  client:
    container_name: logs-client-01
    build: ./client
    environment:
      BASE_URL: 'http://logs-app-01:8080'

  filebeat:
    container_name: logs-filebeat-01
    build:
      context: ./filebeat
      args:
        ELASTIC_STACK_VERSION: '8.6.0'
    volumes:
      - shared-volume:/var/log/app/
      - ./01-filebeat.yml:/usr/share/filebeat/filebeat.yml
    environment:
      # authentication, values provided through .env file
      elasticsearch_host: "${elasticsearch_host}"
      cloud_id: "${cloud_id}"
      cloud_auth: "${cloud_auth}"
      # path to log file
      app_log: /var/log/app/app.log
      # name of the service, should be equal to ELASTIC_APM_SERVICE_NAME
      service_name: app-01

volumes:
  shared-volume:
