
# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: filestream
  id: 01-plaintext-filestream
  enabled: true
  paths:
    - ${app_log}
  parsers:
  - multiline:
      type: pattern
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after
  # add service fields
  fields_under_root: true
  fields:
    service.name: ${service_name}
    service.environment: ${service_environment}
    event.dataset: ${service_name}

output.elasticsearch:
  hosts: [ "https://${elasticsearch_host:CHANGEME}" ]
  pipeline: log-ingest-plaintext

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
