version: '3'

services:

  app:
    container_name: logs-app
    build: ./app
    ports:
      - '8080:8080'
    volumes:
      - shared-volume:/var/log/app/
      - ./01-plaintext-filebeat-config.yml:/usr/share/filebeat/filebeat.yml:ro
    environment:
      # defaults taken from https://github.com/spring-projects/spring-boot/blob/v3.0.1/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml
      # default format for console prefixed with correlation IDs + some colors for easy visualization
      CONSOLE_LOG_PATTERN: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} %5p ${PID:- } --- [%15.15t] (%-40.40logger{39}: %m --- %clr(%X{trace.id}){yellow},%clr(%X{transaction.id}){magenta},%clr(%X{error.id}){red}%n%wEx'
      # default format in file prefixed with correlation IDs
      FILE_LOG_PATTERN: '%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX} %5p ${PID:- } --- [%t] (%-40.40logger{39}: %m --- %X{trace.id},%X{transaction.id},%X{error.id}%n%wEx'
      # make the app also write logs to file
      LOGGING_FILE_NAME: /var/log/app/app.log

  client:
    container_name: logs-client
    build: ./client
    environment:
      BASE_URL: 'http://logs-app:8080'

  filebeat:
    container_name: logs-filebeat
    build:
      context: ./filebeat
      args:
        ELASTIC_STACK_VERSION: '8.5.3'
    volumes:
      - shared-volume:/var/log/app/
    environment:
      # authentication, values provided through .env file
      elasticsearch_host: "${elasticsearch_host}"
      cloud_id: "${cloud_id}"
      cloud_auth: "${cloud_auth}"
      # path to log file
      app_log: /var/log/app/app.log
      # required to run filebeat in docker
      strict.perms: 'false'

volumes:
  shared-volume:
