
# ============================== Filebeat inputs ===============================

filebeat.inputs:

- type: filestream
  id: 02-ecs-filestream
  enabled: true
  paths:
    - ${app_log}
  parsers:
    - ndjson:
        overwrite_keys: true
        add_error_key: true
        expand_keys: true

# =============================== Elastic Cloud ================================

cloud.id: "${cloud_id:CHANGEME}"
cloud.auth: "${cloud_auth:CHANGEME}"

# ================================== Outputs ===================================

output.elasticsearch:
  hosts: [ "https://${elasticsearch_host:CHANGEME}" ]

# ================================= Processors =================================
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
