version: '3.9'

services:

  app:
    container_name: logs-app-05
    build: ./app
    ports:
      - '8084:8080'
    environment:
      OTEL_RESOURCE_ATTRIBUTES: "service.name=app-05,service.version=1.0,deployment.environment=dev"
      OTEL_EXPORTER_OTLP_ENDPOINT: "${apm_server_url}"
      OTEL_EXPORTER_OTLP_HEADERS: "Authorization=Bearer ${apm_secret_token}"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "otlp"

  client:
    container_name: logs-client-05
    build: ./client
    environment:
      BASE_URL: 'http://logs-app-05:8080'
