{
  "networks": {
    "default": {
      "name": "apm-integration-testing"
    }
  },
  "services": {
    "apm-server": {
      "cap_add": [
        "CHOWN",
        "DAC_OVERRIDE",
        "SETGID",
        "SETUID"
      ],
      "cap_drop": [
        "ALL"
      ],
      "command": [
        "apm-server",
        "-e",
        "--httpprof",
        ":6060",
        "-E",
        "apm-server.rum.enabled=true",
        "-E",
        "apm-server.rum.event_rate.limit=1000",
        "-E",
        "apm-server.host=0.0.0.0:8200",
        "-E",
        "apm-server.read_timeout=1m",
        "-E",
        "apm-server.shutdown_timeout=2m",
        "-E",
        "apm-server.write_timeout=1m",
        "-E",
        "logging.json=true",
        "-E",
        "logging.metrics.enabled=false",
        "-E",
        "setup.template.settings.index.number_of_replicas=0",
        "-E",
        "setup.template.settings.index.number_of_shards=1",
        "-E",
        "setup.template.settings.index.refresh_interval=1ms",
        "-E",
        "monitoring.elasticsearch=true",
        "-E",
        "monitoring.enabled=true",
        "-E",
        "apm-server.rum.allow_headers=[\"x-custom-header\"]",
        "-E",
        "apm-server.instrumentation.enabled=true",
        "-E",
        "apm-server.instrumentation.profiling.cpu.enabled=true",
        "-E",
        "apm-server.instrumentation.profiling.heap.enabled=true",
        "-E",
        "apm-server.mode=experimental",
        "-E",
        "apm-server.kibana.enabled=true",
        "-E",
        "apm-server.kibana.host=kibana:5601",
        "-E",
        "apm-server.agent.config.cache.expiration=30s",
        "-E",
        "apm-server.jaeger.http.enabled=true",
        "-E",
        "apm-server.jaeger.http.host=0.0.0.0:14268",
        "-E",
        "apm-server.jaeger.grpc.enabled=true",
        "-E",
        "apm-server.jaeger.grpc.host=0.0.0.0:14250",
        "-E",
        "apm-server.sampling.keep_unsampled=true",
        "-E",
        "output.elasticsearch.hosts=[\"http://elasticsearch:9200\"]",
        "-E",
        "output.elasticsearch.enabled=true",
        "-E",
        "output.elasticsearch.pipelines=[{pipeline: 'apm'}]",
        "-E",
        "apm-server.register.ingest.pipeline.enabled=true"
      ],
      "container_name": "localtesting_${STACK_VERSION:-7.17.6}_apm-server",
      "depends_on": {
        "elasticsearch": {
          "condition": "service_healthy"
        },
        "kibana": {
          "condition": "service_healthy"
        }
      },
      "environment": [
        "BEAT_STRICT_PERMS=false"
      ],
      "healthcheck": {
        "interval": "10s",
        "retries": 12,
        "test": [
          "CMD",
          "curl",
          "--write-out",
          "'HTTP %{http_code}'",
          "-k",
          "--fail",
          "--silent",
          "--output",
          "/dev/null",
          "http://localhost:8200/"
        ],
        "timeout": "5s"
      },
      "image": "docker.elastic.co/apm/apm-server:${STACK_VERSION:-7.17.6}",
      "labels": [
        "co.elastic.apm.stack-version=${STACK_VERSION:-7.17.6}"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:8200:8200",
        "127.0.0.1:6060:6060",
        "127.0.0.1:14268:14268",
        "127.0.0.1:14250:14250"
      ]
    },
    "elasticsearch": {
      "container_name": "localtesting_${STACK_VERSION:-7.17.6}_elasticsearch",
      "environment": [
        "bootstrap.memory_lock=true",
        "cluster.name=docker-cluster",
        "cluster.routing.allocation.disk.threshold_enabled=false",
        "discovery.type=single-node",
        "path.repo=/usr/share/elasticsearch/data/backups",
        "ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g",
        "path.data=/usr/share/elasticsearch/data/${STACK_VERSION:-7.17.6}",
        "xpack.security.enabled=false",
        "xpack.license.self_generated.type=trial",
        "xpack.monitoring.collection.enabled=true"
      ],
      "healthcheck": {
        "interval": "20s",
        "retries": 10,
        "test": [
          "CMD-SHELL",
          "curl -s -k http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"
        ]
      },
      "image": "docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION:-7.17.6}",
      "labels": [
        "co.elastic.apm.stack-version=${STACK_VERSION:-7.17.6}",
        "co.elastic.metrics/module=elasticsearch",
        "co.elastic.metrics/metricsets=node,node_stats",
        "co.elastic.metrics/hosts=http://$${data.host}:9200"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:9200:9200"
      ],
      "ulimits": {
        "memlock": {
          "hard": -1,
          "soft": -1
        }
      },
      "volumes": [
        "esdata:/usr/share/elasticsearch/data"
      ]
    },
    "kibana": {
      "container_name": "localtesting_${STACK_VERSION:-7.17.6}_kibana",
      "depends_on": {
        "elasticsearch": {
          "condition": "service_healthy"
        }
      },
      "environment": {
        "ELASTICSEARCH_HOSTS": "http://elasticsearch:9200",
        "SERVER_HOST": "0.0.0.0",
        "SERVER_NAME": "kibana.example.org",
        "TELEMETRY_ENABLED": "false",
        "XPACK_APM_SERVICEMAPENABLED": "true",
        "XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY": "fhjskloppd678ehkdfdlliverpoolfcr",
        "XPACK_FLEET_AGENTS_ELASTICSEARCH_HOST": "http://elasticsearch:9200",
        "XPACK_FLEET_AGENTS_KIBANA_HOST": "http://kibana:5601",
        "XPACK_MONITORING_ENABLED": "true",
        "XPACK_SECURITY_ENCRYPTIONKEY": "fhjskloppd678ehkdfdlliverpoolfcr",
        "XPACK_XPACK_MAIN_TELEMETRY_ENABLED": "false"
      },
      "healthcheck": {
        "interval": "10s",
        "retries": 30,
        "start_period": "10s",
        "test": [
          "CMD",
          "curl",
          "--write-out",
          "'HTTP %{http_code}'",
          "-k",
          "--fail",
          "--silent",
          "--output",
          "/dev/null",
          "http://kibana:5601/api/status"
        ],
        "timeout": "5s"
      },
      "image": "docker.elastic.co/kibana/kibana:${STACK_VERSION:-7.17.6}",
      "labels": [
        "co.elastic.apm.stack-version=${STACK_VERSION:-7.17.6}"
      ],
      "logging": {
        "driver": "json-file",
        "options": {
          "max-file": "5",
          "max-size": "2m"
        }
      },
      "ports": [
        "127.0.0.1:5601:5601"
      ]
    },
    "wait-service": {
      "container_name": "wait",
      "depends_on": {
        "apm-server": {
          "condition": "service_healthy"
        },
        "elasticsearch": {
          "condition": "service_healthy"
        },
        "kibana": {
          "condition": "service_healthy"
        }
      },
      "image": "busybox"
    }
  },
  "version": "2.4",
  "volumes": {
    "esdata": {
      "driver": "local"
    },
    "pgdata": {
      "driver": "local"
    }
  }
}