---
apm_server:
  cluster: ['manage_ilm', 'manage_security', 'manage_api_key']
  indices:
    - names: ['apm-*']
      privileges: ['write', 'create_index', 'manage', 'manage_ilm']
  applications:
    - application: 'apm-backend'
      privileges: ['action:access', 'action:intake', 'action:sourcemap', 'action:config', 'action:full']
      resources: '*'
