receivers:
  otlp:
    endpoint: 0.0.0.0:55678

exporters:
  elastic:
    apm_server_url: "http://apm-server:8200"

processors:
  batch:
  queued_retry:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [elastic]
      processors: [batch, queued_retry]
