receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:55680
      http:
        endpoint: 0.0.0.0:55681


exporters:
  logging:
    loglevel: debug
  otlp/http:
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}" 
    tls:
      ca_file: /config/certs/ca/ca.crt



service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [logging, otlp/http]
    metrics:
      receivers: [otlp]
      exporters: [logging, otlp/http]
    logs:
      receivers: [otlp]
      exporters: [logging, otlp/http]