version: "2"
services:

  frontend:
    build:
      context: ./otel-js-frontend
    depends_on:
      - apm-server
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: apm-server:8200
      OTEL_EXPORTER_OTLP_TRACES_INSECURE: true

  backend:
    build:
      context: ./otel-python-backend
    depends_on:
      - apm-server
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: apm-server:8200
      OTEL_EXPORTER_OTLP_TRACES_INSECURE: true

  pinger:
    build:
      context: ./elastic-pinger
    environment:
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
    depends_on:
      - apm-server

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.6
    command:
      - -e
      - --E
      - output.elasticsearch.hosts=["elasticsearch:9200"]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.6
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.6
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

